name: one_click_flowers
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  bottom_navy_bar: ^6.0.0
  smooth_page_indicator: ^1.1.0
  flutter_rating_bar: ^4.0.1
  font_awesome_flutter: ^10.4.0
  animations: ^2.0.7
  carousel_slider: ^4.2.1
  intl: 0.18.1
  flutter_animate: ^4.2.0+1
  url_launcher: ^6.1.14

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/image/product/
    - assets/image/slider/
    - assets/image/instagram/
    - assets/image/logo/
    - assets/image/onboarding/
    - assets/image/partners/